AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'spec/spec_helper.rb'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
