AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Style/StringConcatenation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
