# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: intacct 0 ruby lib

Gem::Specification.new do |s|
  s.name = "intacct".freeze
  s.version = "0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["David Paluy".freeze, "Yaroslav Konovets".freeze]
  s.date = "1980-01-02"
  s.description = "Sage Intacct API wrapper".freeze
  s.email = "dpaluy@users.noreply.github.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "intacct.gemspec",
    "lib/intacct.rb",
    "lib/intacct/authentication_methods/credentials.rb",
    "lib/intacct/authentication_methods/session.rb",
    "lib/intacct/authentication_result.rb",
    "lib/intacct/config.rb",
    "lib/intacct/exceptions/client_exception.rb",
    "lib/intacct/exceptions/function_failure_exception.rb",
    "lib/intacct/exceptions/missing_authentication_exception.rb",
    "lib/intacct/function_result.rb",
    "lib/intacct/functions/create.rb",
    "lib/intacct/functions/create_ar_adjustment.rb",
    "lib/intacct/functions/get_api_session.rb",
    "lib/intacct/functions/query.rb",
    "lib/intacct/functions/read.rb",
    "lib/intacct/functions/retrieve_pdf.rb",
    "lib/intacct/functions/reverse_payment.rb",
    "lib/intacct/functions/update.rb",
    "lib/intacct/gateway.rb",
    "lib/intacct/request.rb",
    "lib/intacct/response.rb",
    "lib/intacct/utils.rb",
    "lib/intacct/version.rb",
    "spec/intacct/client_spec.rb",
    "spec/intacct_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/dpaluy/intacct".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.7.2".freeze
  s.summary = "Sage Intacct API wrapper".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<faraday>.freeze, ["~> 1.10.0".freeze])
  s.add_runtime_dependency(%q<json>.freeze, ["~> 2.7".freeze])
  s.add_development_dependency(%q<bundler>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.4.9".freeze])
  s.add_development_dependency(%q<pry-byebug>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<rdoc>.freeze, ["~> 6.0".freeze])
  s.add_development_dependency(%q<rspec>.freeze, ["~> 3.11.0".freeze])
  s.add_development_dependency(%q<shoulda>.freeze, ["~> 4.0.0".freeze])
  s.add_development_dependency(%q<simplecov>.freeze, [">= 0.21.0".freeze])
  s.add_development_dependency(%q<timecop>.freeze, ["~> 0.9.0".freeze])
  s.add_development_dependency(%q<webmock>.freeze, ["~> 3.18.0".freeze])
  s.add_development_dependency(%q<codeclimate-test-reporter>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<coveralls>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<rubocop>.freeze, [">= 0".freeze])
end

